name: Release

on:
  workflow_dispatch:

jobs:
  config-release-file:
    name: Configure Release file
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Release file
        run: make release-config

      - name: Commit Release file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Configure Release file"
